import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import banner from '../public/images/daytonAerial.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Developer Resume</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <h1 className={styles.heading}>
        Home
      </h1>
      <Image 
        src={banner} 
        alt="Aerial view of Dayton, Ohio"
        width={1949}
        height={779}
        className={styles.banner} />
      
    </div>
  )
}
